services:
  db:
    image: postgres:15
    container_name: ordem_servico_db
    restart: always
    environment:
      POSTGRES_DB: ordem_servico_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ordem_servico_postgres_data:/var/lib/postgresql/data
    networks:
      - ordem_servico_network

  ordem_servico_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ordem_servico_app
    restart: always
    ports:
      - "8080:8080" # Assuming Spring Boot app runs on 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ordem_servico_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    networks:
      - ordem_servico_network

volumes:
  ordem_servico_postgres_data:

networks:
  ordem_servico_network: