server:
  port: ${SERVER_PORT:8088}

spring:
  flyway:
    enabled: true
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always

jwt:
  key: ${JWT_KEY}

feign:
  client:
    config:
      cliente-service:
        url: ${FEIGN_CLIENT_CLIENTE_URL}
      catalogo-service:
        url: ${FEIGN_CLIENT_CATALOGO_URL}
      orcamento-service:
        url: ${FEIGN_CLIENT_ORCAMENTO_URL}
      pagamento-service:
        url: ${FEIGN_CLIENT_PAGAMENTO_URL}

aws:
  region: ${AWS_REGION:us-east-1}
  sqs:
    payment-queue-url: ${AWS_SQS_PAYMENT_QUEUE_URL}
    endpoint-override: ${AWS_SQS_ENDPOINT_OVERRIDE:}
    polling-interval-ms: ${AWS_SQS_POLLING_INTERVAL:5000}

otel:
  service:
    name: ${OTEL_SERVICE_NAME:ordem-servico}
    resource:
      attributes:
        environment: ${OTEL_ENVIRONMENT}
        version: ${OTEL_VERSION}
        team: backend

  traces:
    exporter: otlp
    endpoint: ${OTEL_ENDPOINT}
    sampler: always_on

  metrics:
    exporter: otlp
    endpoint: ${OTEL_ENDPOINT}

  logs:
    exporter: none

  instrumentation:
    spring-webmvc:
      enabled: true
    jdbc:
      enabled: true
    logback-appender:
      enabled: true
    micrometer:
      enabled: true
