apiVersion: v1
kind: Service
metadata:
  name: ordem-servico-app-service
  labels:
    app: ordem-servico-app
spec:
  type: ClusterIP
  selector:
    app: ordem-servico-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
