apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-configmap.yaml
  - ordem-servico-secret.yaml
  - app-deployment.yaml
  - app-service.yaml
  - app-hpa.yaml

namePrefix: ordem-servico-
namespace: oficina-ns
