apiVersion: v1
kind: Secret
metadata:
  name: ordem-servico-secret
  namespace: oficina-ns
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: DB_PASSWORD_PLACEHOLDER
  JWT_KEY: JWT_KEY_PLACEHOLDER
