apiVersion: v1
kind: Secret
metadata:
  name: ordem-servico-secret
  namespace: oficina-ns
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: DB_PASSWORD_PLACEHOLDER
  RDS_URL: RDS_URL_PLACEHOLDER
  AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID_PLACEHOLDER
  AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY_PLACEHOLDER
  AWS_SESSION_TOKEN: AWS_SESSION_TOKEN_PLACEHOLDER
