name: CI Pipeline - Ordem Servico

on:
  push:
    branches:
      - 'feature/**'
    paths:
      - 'ordem_servico/**' # Only run when changes are in the ordem_servico directory

jobs:
  build-and-test:
    name: Build e Testes - Ordem Servico
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      working-directory: ordem_servico/

  validate-docker:
    name: Validação Docker - Ordem Servico
    needs: build-and-test
    uses: ./.github/workflows/reusable-docker.yml
    secrets: inherit
    with:
      context: ordem_servico/
      dockerfile: ordem_servico/Dockerfile

  create-pull-request:
    name: Criar Pull Request - Ordem Servico
    needs: [validate-docker]
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/reusable-pr.yml
    secrets: inherit
    with:
      branch-name: ${{ github.ref_name }}